template: |
  ## What's Changed
  - PR Title 1
  - PR Title 2

  ## New Features
  - Add any new features or improvements here

  ## Bug Fixes
  - Describe any bug fixes here

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
categories:
  - title: '🚀 New Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🛠 Maintenance'
    labels:
      - maintenance
