template: |
  ## 🚀 What's New
  Here are the updates since the last release:

  ### New Features
  $CHANGES

change-template: '- $TITLE ([#$NUMBER]($URL)) by @$AUTHOR'
categories:
  - title: '🚀 New Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🛠 Maintenance'
    labels:
      - maintenance
